spring:
  application:
    name: story
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:${MYSQL_PORT}/story?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}
    consumer:
      auto-offset-reset: latest
      group-id: story
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: ${JWT_SECRET}

client:
  origin: ${DOMAIN_IP}